# Generated by Django 2.2.5 on 2020-12-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201201_2000'),
        ('users', '0002_auto_20201201_1524'),
    ]

    operations = [
    ]
