# Generated by Django 2.2.5 on 2020-12-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201201_1526'),
        ('rooms', '0005_auto_20201201_1853'),
    ]

    operations = [
    ]
