# Generated by Django 2.2.5 on 2020-12-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20201202_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility',
            new_name='Amenities',
        ),
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Facilities',
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='facilities',
        ),
    ]
