# Generated by Django 2.2.5 on 2020-12-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20201208_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.RenameModel(
            old_name='Facilities',
            new_name='Facility',
        ),
    ]
