# Generated by Django 2.2.5 on 2020-12-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201201_1853'),
        ('reservations', '0002_auto_20201201_1524'),
    ]

    operations = [
    ]
