# Generated by Django 2.2.5 on 2021-01-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_bookedday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='geust',
            new_name='guest',
        ),
    ]
