# Generated by Django 2.2.5 on 2020-12-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_merge_20201202_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='rooms',
            new_name='room',
        ),
    ]
